[package]
name = "traitmap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
dyn-clone = "1.0.4"
static_assertions = "1.1.0"
